_target_: tokenized_complex

data_dir: ${paths.data_dir}
# dataloader related
max_tokens: 4000
max_len: 1018
num_workers: 4
csv_file: SAbDab
vocab_file: /mnt/shared-storage-user/wangjie3/Diffs/dplm/weights/DPLM2/vocab.txt

length_crop: true
cluster_training: false
min_crop_length: 60

struct_vocab_size: 8192
